//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSystemConfigurationExample.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class MoreSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MoreSettings defaultInstance = ((MoreSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MoreSettings())));
        
        public static MoreSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I\'m the User setting that can be modified and can be written out to a specially n" +
            "amed (unique to each binary) location in %AppData%.")]
        public string MoreSettingsUserSetting {
            get {
                return ((string)(this["MoreSettingsUserSetting"]));
            }
            set {
                this["MoreSettingsUserSetting"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("I\'m an Application Setting that can be overridden from the app.config but can\'t b" +
            "e modified by the application.")]
        public string MoreSettingsApplicationSetting {
            get {
                return ((string)(this["MoreSettingsApplicationSetting"]));
            }
        }
    }
}
